services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: markwbromwich
      POSTGRES_PASSWORD: xzsX3Rb2ZvsV1lMDkByKQW299DOxlErS
      POSTGRES_DB: foodapp_gltw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:postgresql://markwbromwich:xzsX3Rb2ZvsV1lMDkByKQW299DOxlErS@dpg-d6bltdd6ubrc73cn9ohg-a/foodapp_gltw
    restart: unless-stopped
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "5432:5432"

volumes:
  pgdata:
